### ISSUE TITLE
The manager fails to run after update

### ISSUE THREAD

**Issue by Erzis900** [RotorHazard/RH_Install-Manager#13]
```Traceback (most recent call last):
  File "/home/dron/RH_Install-Manager/start_rhim.py", line 33, in <module>
    main()
  File "/home/dron/RH_Install-Manager/start_rhim.py", line 29, in main
    update.main()
  File "/home/dron/RH_Install-Manager/update.py", line 572, in main
    main_menu(config)
  File "/home/dron/RH_Install-Manager/update.py", line 513, in main_menu
    if not rhim_config.first_part_of_install and not rhim_config.second_part_of_install:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'first_part_of_install'
```
It worked perfectly fine before I updated it.

**Comment by szafranski** [comment]
Looks like you have put wrong username. Regardless - please tell if issue is still present

**Comment by creecedev** [comment]
I am running into this same issue. I updated and the install manager will not start with the same error as above. I have tried re-installing the install manager and can get to the configuration and enter in my username and everything but then right back to the error.

**Comment by szafranski** [comment]
please paste the output of the command:

cat ~/RH_Install-Manager/updater-config.json 

?

**Comment by creecedev** [comment]
Unfortunately I did a full reinstall (Pi and RotorHazard software via RH Install Manager) so would not have the correct info for you any longer. Reinstalling did fix my issue so I guess there is _a_ workaround for this.

**Comment by szafranski** [comment]
Ok, sure. So it works now?

**Comment by creecedev** [comment]
Yes, everything is working after completely reinstalling Raspberry Pi OS and RH.

**Comment by szafranski** [comment]
Ok, thanks for reporting. Please write if anything else is needed
